services:
  postgres:
    image: postgres:16-alpine
    container_name: fleet-manager-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: fleet
      POSTGRES_PASSWORD: fleet123
      POSTGRES_DB: fleet_manager
      POSTGRES_HOST_AUTH_METHOD: trust
      PGTZ: America/Argentina/Buenos_Aires
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
